[OK]#[OK]![OK]/[OK]u[OK]s[OK]r[OK]/[OK]b[OK]i[OK]n[OK]/[OK]e[OK]n[OK]v[OK] [OK]p[OK]y[OK]t[OK]h[OK]o[OK]n[OK]3[OK][OK]
[OK]"[OK]"[OK]"[OK][OK]
[OK]A[OK]u[OK]t[OK]o[OK]m[OK]a[OK]t[OK]e[OK]d[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK] [OK]t[OK]o[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK] [OK]f[OK]r[OK]o[OK]m[OK] [OK]m[OK]a[OK]i[OK]n[OK].[OK]p[OK]y[OK].[OK][OK]
[OK][OK]
[OK]T[OK]h[OK]i[OK]s[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK] [OK]i[OK]d[OK]e[OK]n[OK]t[OK]i[OK]f[OK]i[OK]e[OK]s[OK] [OK]a[OK]n[OK]d[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]s[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]t[OK]h[OK]a[OK]t[OK] [OK]a[OK]r[OK]e[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]d[OK] [OK]i[OK]n[OK] [OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]s[OK],[OK][OK]
[OK]l[OK]e[OK]a[OK]v[OK]i[OK]n[OK]g[OK] [OK]o[OK]n[OK]l[OK]y[OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]w[OK]h[OK]e[OK]r[OK]e[OK] [OK]t[OK]h[OK]e[OK]y[OK] [OK]w[OK]e[OK]r[OK]e[OK] [OK]m[OK]o[OK]v[OK]e[OK]d[OK].[OK][OK]
[OK]"[OK]"[OK]"[OK][OK]
[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]r[OK]e[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]p[OK]a[OK]t[OK]h[OK]l[OK]i[OK]b[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]P[OK]a[OK]t[OK]h[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]t[OK]y[OK]p[OK]i[OK]n[OK]g[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]L[OK]i[OK]s[OK]t[OK],[OK] [OK]T[OK]u[OK]p[OK]l[OK]e[OK][OK]
[OK][OK]
[OK]#[OK] [OK]D[OK]e[OK]f[OK]i[OK]n[OK]e[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK] [OK]t[OK]o[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]([OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]p[OK]a[OK]t[OK]h[OK],[OK] [OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]f[OK]i[OK]l[OK]e[OK],[OK] [OK]a[OK]p[OK]p[OK]r[OK]o[OK]x[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK][OK]
[OK]D[OK]U[OK]P[OK]L[OK]I[OK]C[OK]A[OK]T[OK]E[OK]S[OK]_[OK]T[OK]O[OK]_[OK]R[OK]E[OK]M[OK]O[OK]V[OK]E[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK] [OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]g[OK]e[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]s[OK]u[OK]g[OK]g[OK]e[OK]s[OK]t[OK]-[OK]m[OK]e[OK]r[OK]g[OK]e[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]2[OK]5[OK]2[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]G[OK]E[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]s[OK]u[OK]g[OK]g[OK]e[OK]s[OK]t[OK]-[OK]m[OK]e[OK]r[OK]g[OK]e[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]m[OK]e[OK]r[OK]g[OK]e[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]2[OK]7[OK]3[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]m[OK]e[OK]r[OK]g[OK]e[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]\[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]d[OK]b[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]s[OK]p[OK]l[OK]i[OK]t[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]3[OK]0[OK]6[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]d[OK]b[OK]_[OK]i[OK]d[OK]}[OK]/[OK]s[OK]p[OK]l[OK]i[OK]t[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]l[OK]i[OK]n[OK]k[OK]_[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]3[OK]2[OK]5[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]l[OK]i[OK]n[OK]k[OK]_[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]n[OK]o[OK]t[OK]e[OK]"[OK]:[OK] [OK]"[OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]u[OK]s[OK]e[OK]s[OK] [OK]/[OK]l[OK]i[OK]n[OK]k[OK] [OK]i[OK]n[OK]s[OK]t[OK]e[OK]a[OK]d[OK] [OK]o[OK]f[OK] [OK]/[OK]l[OK]i[OK]n[OK]k[OK]_[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]u[OK]n[OK]l[OK]i[OK]n[OK]k[OK]_[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]/[OK]\[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]i[OK]d[OK]\[OK]}[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]3[OK]8[OK]2[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]u[OK]n[OK]l[OK]i[OK]n[OK]k[OK]_[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]/[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]i[OK]d[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]n[OK]o[OK]t[OK]e[OK]"[OK]:[OK] [OK]"[OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]u[OK]s[OK]e[OK]s[OK] [OK]D[OK]E[OK]L[OK]E[OK]T[OK]E[OK] [OK]/[OK]u[OK]n[OK]l[OK]i[OK]n[OK]k[OK] [OK]i[OK]n[OK]s[OK]t[OK]e[OK]a[OK]d[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]d[OK]i[OK]s[OK]m[OK]i[OK]s[OK]s[OK]_[OK]m[OK]e[OK]r[OK]g[OK]e[OK]_[OK]s[OK]u[OK]g[OK]g[OK]e[OK]s[OK]t[OK]i[OK]o[OK]n[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]4[OK]1[OK]2[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]d[OK]i[OK]s[OK]m[OK]i[OK]s[OK]s[OK]_[OK]m[OK]e[OK]r[OK]g[OK]e[OK]_[OK]s[OK]u[OK]g[OK]g[OK]e[OK]s[OK]t[OK]i[OK]o[OK]n[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]g[OK]e[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]_[OK]g[OK]r[OK]o[OK]u[OK]p[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]4[OK]2[OK]4[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]G[OK]E[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]_[OK]g[OK]r[OK]o[OK]u[OK]p[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]i[OK]d[OK]/[OK]\[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]d[OK]b[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]4[OK]7[OK]0[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]i[OK]d[OK]/[OK]{[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]d[OK]b[OK]_[OK]i[OK]d[OK]}[OK]/[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]b[OK]a[OK]t[OK]c[OK]h[OK]_[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]4[OK]8[OK]8[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]b[OK]a[OK]t[OK]c[OK]h[OK]_[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]p[OK]r[OK]e[OK]v[OK]i[OK]e[OK]w[OK]-[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]5[OK]2[OK]5[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]p[OK]r[OK]e[OK]v[OK]i[OK]e[OK]w[OK]-[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]n[OK]o[OK]t[OK]e[OK]"[OK]:[OK] [OK]"[OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]u[OK]s[OK]e[OK]s[OK] [OK]/[OK]c[OK]o[OK]n[OK]t[OK]r[OK]o[OK]l[OK]s[OK]/[OK]p[OK]r[OK]e[OK]v[OK]i[OK]e[OK]w[OK]_[OK]m[OK]a[OK]p[OK]p[OK]i[OK]n[OK]g[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]U[OK]E[OK]C[OK] [OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]\[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]a[OK]n[OK]n[OK]o[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]u[OK]e[OK]c[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]}[OK]/[OK]a[OK]n[OK]n[OK]o[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]\[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]\[OK]}[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]u[OK]e[OK]c[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]t[OK]s[OK]c[OK]/[OK]\[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]t[OK]s[OK]c[OK]_[OK]i[OK]d[OK]\[OK]}[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]u[OK]e[OK]c[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]t[OK]s[OK]c[OK]/[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]t[OK]s[OK]c[OK]_[OK]i[OK]d[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]\[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]u[OK]e[OK]c[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]/[OK]{[OK]c[OK]u[OK]e[OK]c[OK]_[OK]i[OK]d[OK]}[OK]/[OK]r[OK]e[OK]c[OK]o[OK]m[OK]p[OK]u[OK]t[OK]e[OK]_[OK]f[OK]r[OK]a[OK]m[OK]e[OK]w[OK]o[OK]r[OK]k[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]c[OK]u[OK]e[OK]c[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]c[OK]u[OK]e[OK]c[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]u[OK]b[OK]o[OK]r[OK]g[OK] [OK]R[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]i[OK]d[OK]/[OK]\[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]i[OK]d[OK]\[OK]}[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]i[OK]d[OK]/[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]i[OK]d[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]\[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]a[OK]n[OK]n[OK]o[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]i[OK]d[OK]}[OK]/[OK]a[OK]n[OK]n[OK]o[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]a[OK]t[OK]c[OK]h[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]\[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]n[OK]a[OK]m[OK]e[OK]\[OK]}[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]A[OK]T[OK]C[OK]H[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]/[OK]{[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]n[OK]a[OK]m[OK]e[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]:[OK] [OK]r[OK]'[OK]@[OK]a[OK]p[OK]p[OK]\[OK].[OK]p[OK]o[OK]s[OK]t[OK]\[OK]([OK]"[OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]\[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]\[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]"[OK]\[OK])[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]:[OK] [OK]"[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]_[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK].[OK]p[OK]y[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]"[OK]P[OK]O[OK]S[OK]T[OK] [OK]/[OK]r[OK]e[OK]p[OK]o[OK]r[OK]t[OK]/[OK]{[OK]s[OK]c[OK]a[OK]n[OK]_[OK]i[OK]d[OK]}[OK]/[OK]s[OK]u[OK]b[OK]o[OK]r[OK]g[OK]s[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK],[OK][OK]
[OK]][OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]f[OK]i[OK]n[OK]d[OK]_[OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]b[OK]o[OK]u[OK]n[OK]d[OK]a[OK]r[OK]i[OK]e[OK]s[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK]:[OK] [OK]L[OK]i[OK]s[OK]t[OK][[OK]s[OK]t[OK]r[OK]][OK],[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK]:[OK] [OK]i[OK]n[OK]t[OK])[OK] [OK]-[OK]>[OK] [OK]T[OK]u[OK]p[OK]l[OK]e[OK][[OK]i[OK]n[OK]t[OK],[OK] [OK]i[OK]n[OK]t[OK]][OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]F[OK]i[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK] [OK]a[OK]n[OK]d[OK] [OK]e[OK]n[OK]d[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK] [OK]o[OK]f[OK] [OK]a[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]d[OK]e[OK]f[OK]i[OK]n[OK]i[OK]t[OK]i[OK]o[OK]n[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]A[OK]r[OK]g[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]:[OK] [OK]L[OK]i[OK]s[OK]t[OK] [OK]o[OK]f[OK] [OK]f[OK]i[OK]l[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK]:[OK] [OK]I[OK]n[OK]d[OK]e[OK]x[OK] [OK]o[OK]f[OK] [OK]t[OK]h[OK]e[OK] [OK]d[OK]e[OK]c[OK]o[OK]r[OK]a[OK]t[OK]o[OK]r[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]([OK]@[OK]a[OK]p[OK]p[OK].[OK]g[OK]e[OK]t[OK],[OK] [OK]e[OK]t[OK]c[OK].[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]R[OK]e[OK]t[OK]u[OK]r[OK]n[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]T[OK]u[OK]p[OK]l[OK]e[OK] [OK]o[OK]f[OK] [OK]([OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK],[OK] [OK]e[OK]n[OK]d[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]s[OK]h[OK]o[OK]u[OK]l[OK]d[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK] [OK]a[OK]t[OK] [OK]t[OK]h[OK]e[OK] [OK]d[OK]e[OK]c[OK]o[OK]r[OK]a[OK]t[OK]o[OK]r[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]u[OK]n[OK]c[OK]_[OK]s[OK]t[OK]a[OK]r[OK]t[OK] [OK]=[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]i[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]'[OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK]'[OK] [OK]l[OK]i[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK] [OK]=[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK],[OK] [OK]m[OK]i[OK]n[OK]([OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]i[OK]d[OK]x[OK] [OK]+[OK] [OK]5[OK],[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK])[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]i[OK]][OK].[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]'[OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]'[OK])[OK] [OK]o[OK]r[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]i[OK]][OK].[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]'[OK]d[OK]e[OK]f[OK] [OK]'[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]N[OK]o[OK]w[OK] [OK]f[OK]i[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]e[OK]n[OK]d[OK] [OK]o[OK]f[OK] [OK]t[OK]h[OK]e[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]b[OK]y[OK] [OK]t[OK]r[OK]a[OK]c[OK]k[OK]i[OK]n[OK]g[OK] [OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]h[OK]e[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]e[OK]n[OK]d[OK]s[OK] [OK]w[OK]h[OK]e[OK]n[OK] [OK]w[OK]e[OK] [OK]e[OK]n[OK]c[OK]o[OK]u[OK]n[OK]t[OK]e[OK]r[OK] [OK]a[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]a[OK]t[OK] [OK]t[OK]h[OK]e[OK] [OK]s[OK]a[OK]m[OK]e[OK] [OK]o[OK]r[OK] [OK]l[OK]o[OK]w[OK]e[OK]r[OK] [OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]s[OK] [OK]t[OK]h[OK]e[OK] [OK]'[OK]d[OK]e[OK]f[OK]'[OK] [OK]l[OK]i[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK]_[OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]d[OK]e[OK]f[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK]][OK])[OK] [OK]-[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]d[OK]e[OK]f[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK]][OK].[OK]l[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK] [OK]=[OK] [OK]d[OK]e[OK]f[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]i[OK]d[OK]x[OK] [OK]+[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]n[OK]_[OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]c[OK]h[OK]a[OK]r[OK] [OK]=[OK] [OK]N[OK]o[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]d[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK] [OK] [OK]#[OK] [OK]O[OK]n[OK]l[OK]y[OK] [OK]t[OK]r[OK]e[OK]a[OK]t[OK] [OK]f[OK]i[OK]r[OK]s[OK]t[OK] [OK]"[OK]"[OK]"[OK] [OK]o[OK]r[OK] [OK]'[OK]'[OK]'[OK] [OK]a[OK]s[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]h[OK]i[OK]l[OK]e[OK] [OK]i[OK] [OK]<[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]=[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]i[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK] [OK]=[OK] [OK]l[OK]i[OK]n[OK]e[OK].[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]H[OK]a[OK]n[OK]d[OK]l[OK]e[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]([OK]o[OK]n[OK]l[OK]y[OK] [OK]t[OK]h[OK]e[OK] [OK]f[OK]i[OK]r[OK]s[OK]t[OK] [OK]o[OK]n[OK]e[OK] [OK]a[OK]f[OK]t[OK]e[OK]r[OK] [OK]d[OK]e[OK]f[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]d[OK] [OK]a[OK]n[OK]d[OK] [OK]n[OK]o[OK]t[OK] [OK]i[OK]n[OK]_[OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]a[OK]n[OK]d[OK] [OK]([OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]'[OK]"[OK]"[OK]"[OK]'[OK])[OK] [OK]o[OK]r[OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]"[OK]'[OK]'[OK]'[OK]"[OK])[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]c[OK]h[OK]a[OK]r[OK] [OK]=[OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK][[OK]:[OK]3[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]i[OK]f[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]c[OK]l[OK]o[OK]s[OK]e[OK]s[OK] [OK]o[OK]n[OK] [OK]s[OK]a[OK]m[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]([OK]e[OK].[OK]g[OK].[OK],[OK] [OK]"[OK]"[OK]"[OK]S[OK]i[OK]n[OK]g[OK]l[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]"[OK]"[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]o[OK]u[OK]n[OK]t[OK] [OK]o[OK]c[OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]c[OK]e[OK]s[OK] [OK]-[OK] [OK]i[OK]f[OK] [OK]o[OK]d[OK]d[OK] [OK]n[OK]u[OK]m[OK]b[OK]e[OK]r[OK],[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]i[OK]s[OK] [OK]s[OK]t[OK]i[OK]l[OK]l[OK] [OK]o[OK]p[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]=[OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK].[OK]c[OK]o[OK]u[OK]n[OK]t[OK]([OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]c[OK]h[OK]a[OK]r[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]=[OK]=[OK] [OK]1[OK]:[OK] [OK] [OK]#[OK] [OK]O[OK]p[OK]e[OK]n[OK]i[OK]n[OK]g[OK] [OK]o[OK]n[OK]l[OK]y[OK],[OK] [OK]n[OK]o[OK] [OK]c[OK]l[OK]o[OK]s[OK]i[OK]n[OK]g[OK] [OK]o[OK]n[OK] [OK]s[OK]a[OK]m[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]n[OK]_[OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]l[OK]s[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]D[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]o[OK]p[OK]e[OK]n[OK]s[OK] [OK]a[OK]n[OK]d[OK] [OK]c[OK]l[OK]o[OK]s[OK]e[OK]s[OK] [OK]o[OK]n[OK] [OK]s[OK]a[OK]m[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK] [OK]+[OK]=[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]t[OK]i[OK]n[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]i[OK]n[OK]_[OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]c[OK]h[OK]a[OK]r[OK] [OK]i[OK]n[OK] [OK]l[OK]i[OK]n[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]n[OK]_[OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]o[OK]c[OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK] [OK]+[OK]=[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]t[OK]i[OK]n[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]k[OK]i[OK]p[OK] [OK]e[OK]m[OK]p[OK]t[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]a[OK]n[OK]d[OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]-[OK]o[OK]n[OK]l[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK] [OK]o[OK]r[OK] [OK]s[OK]t[OK]r[OK]i[OK]p[OK]p[OK]e[OK]d[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]'[OK]#[OK]'[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK] [OK]+[OK]=[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]t[OK]i[OK]n[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]t[OK]_[OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK])[OK] [OK]-[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK].[OK]l[OK]s[OK]t[OK]r[OK]i[OK]p[OK]([OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]I[OK]f[OK] [OK]w[OK]e[OK] [OK]f[OK]i[OK]n[OK]d[OK] [OK]a[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]a[OK]t[OK] [OK]o[OK]r[OK] [OK]b[OK]e[OK]l[OK]o[OK]w[OK] [OK]t[OK]h[OK]e[OK] [OK]d[OK]e[OK]f[OK] [OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]l[OK]e[OK]v[OK]e[OK]l[OK],[OK] [OK]w[OK]e[OK]'[OK]v[OK]e[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]e[OK]n[OK]d[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]t[OK]_[OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK] [OK]<[OK]=[OK] [OK]d[OK]e[OK]f[OK]_[OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]M[OK]a[OK]k[OK]e[OK] [OK]s[OK]u[OK]r[OK]e[OK] [OK]i[OK]t[OK]'[OK]s[OK] [OK]n[OK]o[OK]t[OK] [OK]a[OK] [OK]c[OK]o[OK]n[OK]t[OK]i[OK]n[OK]u[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]o[OK]f[OK] [OK]t[OK]h[OK]e[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]s[OK]i[OK]g[OK]n[OK]a[OK]t[OK]u[OK]r[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]l[OK]i[OK]n[OK]e[OK][[OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]t[OK]_[OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]:[OK]][OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]s[OK]w[OK]i[OK]t[OK]h[OK]([OK]'[OK])[OK]'[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]o[OK]u[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]e[OK]n[OK]d[OK] [OK]-[OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]t[OK]h[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]b[OK]e[OK]f[OK]o[OK]r[OK]e[OK] [OK]t[OK]h[OK]i[OK]s[OK] [OK]o[OK]n[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]f[OK]u[OK]n[OK]c[OK]_[OK]s[OK]t[OK]a[OK]r[OK]t[OK],[OK] [OK]i[OK] [OK]-[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK] [OK]+[OK]=[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]I[OK]f[OK] [OK]w[OK]e[OK] [OK]r[OK]e[OK]a[OK]c[OK]h[OK] [OK]t[OK]h[OK]e[OK] [OK]e[OK]n[OK]d[OK] [OK]o[OK]f[OK] [OK]f[OK]i[OK]l[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]f[OK]u[OK]n[OK]c[OK]_[OK]s[OK]t[OK]a[OK]r[OK]t[OK],[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK] [OK]-[OK] [OK]1[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]_[OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]([OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK]:[OK] [OK]P[OK]a[OK]t[OK]h[OK],[OK] [OK]d[OK]r[OK]y[OK]_[OK]r[OK]u[OK]n[OK]:[OK] [OK]b[OK]o[OK]o[OK]l[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]R[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]f[OK]r[OK]o[OK]m[OK] [OK]m[OK]a[OK]i[OK]n[OK].[OK]p[OK]y[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]A[OK]r[OK]g[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK]:[OK] [OK]P[OK]a[OK]t[OK]h[OK] [OK]t[OK]o[OK] [OK]m[OK]a[OK]i[OK]n[OK].[OK]p[OK]y[OK] [OK]f[OK]i[OK]l[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]r[OK]y[OK]_[OK]r[OK]u[OK]n[OK]:[OK] [OK]I[OK]f[OK] [OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]o[OK]n[OK]l[OK]y[OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK] [OK]w[OK]h[OK]a[OK]t[OK] [OK]w[OK]o[OK]u[OK]l[OK]d[OK] [OK]b[OK]e[OK] [OK]d[OK]o[OK]n[OK]e[OK] [OK]w[OK]i[OK]t[OK]h[OK]o[OK]u[OK]t[OK] [OK]m[OK]o[OK]d[OK]i[OK]f[OK]y[OK]i[OK]n[OK]g[OK] [OK]f[OK]i[OK]l[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]R[OK]e[OK]a[OK]d[OK]i[OK]n[OK]g[OK] [OK]{[OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK]}[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK],[OK] [OK]'[OK]r[OK]'[OK],[OK] [OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK]=[OK]'[OK]u[OK]t[OK]f[OK]-[OK]8[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]=[OK] [OK]f[OK].[OK]r[OK]e[OK]a[OK]d[OK]l[OK]i[OK]n[OK]e[OK]s[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]=[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]O[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK] [OK]f[OK]i[OK]l[OK]e[OK]:[OK] [OK]{[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]r[OK]a[OK]c[OK]k[OK] [OK]w[OK]h[OK]a[OK]t[OK] [OK]w[OK]e[OK]'[OK]l[OK]l[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]d[OK]u[OK]p[OK] [OK]i[OK]n[OK] [OK]D[OK]U[OK]P[OK]L[OK]I[OK]C[OK]A[OK]T[OK]E[OK]S[OK]_[OK]T[OK]O[OK]_[OK]R[OK]E[OK]M[OK]O[OK]V[OK]E[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK] [OK]=[OK] [OK]d[OK]u[OK]p[OK][[OK]"[OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]"[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]d[OK]u[OK]p[OK][[OK]"[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]"[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]=[OK] [OK]d[OK]u[OK]p[OK][[OK]"[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]"[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]o[OK]t[OK]e[OK] [OK]=[OK] [OK]d[OK]u[OK]p[OK].[OK]g[OK]e[OK]t[OK]([OK]"[OK]n[OK]o[OK]t[OK]e[OK]"[OK],[OK] [OK]"[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]i[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]d[OK]e[OK]c[OK]o[OK]r[OK]a[OK]t[OK]o[OK]r[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]u[OK]m[OK]e[OK]r[OK]a[OK]t[OK]e[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]r[OK]e[OK].[OK]s[OK]e[OK]a[OK]r[OK]c[OK]h[OK]([OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]o[OK]u[OK]n[OK]d[OK] [OK]t[OK]h[OK]e[OK] [OK]d[OK]e[OK]c[OK]o[OK]r[OK]a[OK]t[OK]o[OK]r[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK],[OK] [OK]e[OK]n[OK]d[OK] [OK]=[OK] [OK]f[OK]i[OK]n[OK]d[OK]_[OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]b[OK]o[OK]u[OK]n[OK]d[OK]a[OK]r[OK]i[OK]e[OK]s[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK],[OK] [OK]i[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]=[OK] [OK]e[OK]n[OK]d[OK] [OK]-[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK] [OK]+[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]i[OK]f[OK] [OK]a[OK]l[OK]r[OK]e[OK]a[OK]d[OK]y[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]d[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]i[OK] [OK]>[OK] [OK]0[OK] [OK]a[OK]n[OK]d[OK] [OK]'[OK]#[OK] [OK]R[OK]E[OK]M[OK]O[OK]V[OK]E[OK]D[OK]:[OK]'[OK] [OK]i[OK]n[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]i[OK]-[OK]1[OK]][OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]‚[OK]è[OK]≠[OK]Ô[OK]∏[OK]è[OK] [OK] [OK]S[OK]K[OK]I[OK]P[OK]:[OK] [OK]{[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]}[OK] [OK]-[OK] [OK]A[OK]l[OK]r[OK]e[OK]a[OK]d[OK]y[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]d[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK] [OK]([OK]l[OK]i[OK]n[OK]e[OK] [OK]{[OK]i[OK]+[OK]1[OK]}[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]t[OK]i[OK]n[OK]u[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]s[OK]t[OK]a[OK]r[OK]t[OK]'[OK]:[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]e[OK]n[OK]d[OK]'[OK]:[OK] [OK]e[OK]n[OK]d[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]l[OK]i[OK]n[OK]e[OK]s[OK]'[OK]:[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]'[OK]:[OK] [OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]'[OK]:[OK] [OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]n[OK]o[OK]t[OK]e[OK]'[OK]:[OK] [OK]n[OK]o[OK]t[OK]e[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]d[OK]e[OK]c[OK]o[OK]r[OK]a[OK]t[OK]o[OK]r[OK]_[OK]l[OK]i[OK]n[OK]e[OK]'[OK]:[OK] [OK]i[OK] [OK]+[OK] [OK]1[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]‚[OK]ú[OK]ì[OK] [OK]F[OK]o[OK]u[OK]n[OK]d[OK]:[OK] [OK]{[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]L[OK]i[OK]n[OK]e[OK]s[OK] [OK]{[OK]s[OK]t[OK]a[OK]r[OK]t[OK]+[OK]1[OK]}[OK]-[OK]{[OK]e[OK]n[OK]d[OK]+[OK]1[OK]}[OK] [OK]([OK]{[OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]N[OK]o[OK]w[OK] [OK]i[OK]n[OK]:[OK] [OK]{[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]N[OK]o[OK]t[OK]e[OK]:[OK] [OK]{[OK]n[OK]o[OK]t[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]N[OK]o[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]t[OK]o[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]![OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]o[OK]r[OK]t[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK] [OK]b[OK]y[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]n[OK]u[OK]m[OK]b[OK]e[OK]r[OK] [OK]([OK]d[OK]e[OK]s[OK]c[OK]e[OK]n[OK]d[OK]i[OK]n[OK]g[OK])[OK] [OK]s[OK]o[OK] [OK]w[OK]e[OK] [OK]c[OK]a[OK]n[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]f[OK]r[OK]o[OK]m[OK] [OK]b[OK]o[OK]t[OK]t[OK]o[OK]m[OK] [OK]t[OK]o[OK] [OK]t[OK]o[OK]p[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK].[OK]s[OK]o[OK]r[OK]t[OK]([OK]k[OK]e[OK]y[OK]=[OK]l[OK]a[OK]m[OK]b[OK]d[OK]a[OK] [OK]x[OK]:[OK] [OK]x[OK][[OK]'[OK]s[OK]t[OK]a[OK]r[OK]t[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]v[OK]e[OK]r[OK]s[OK]e[OK]=[OK]T[OK]r[OK]u[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]=[OK] [OK]s[OK]u[OK]m[OK]([OK]r[OK][[OK]'[OK]l[OK]i[OK]n[OK]e[OK]s[OK]'[OK]][OK] [OK]f[OK]o[OK]r[OK] [OK]r[OK] [OK]i[OK]n[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]{[OK]'[OK]=[OK]'[OK]*[OK]7[OK]0[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]S[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK]:[OK] [OK]F[OK]o[OK]u[OK]n[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK])[OK]}[OK] [OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]T[OK]o[OK]t[OK]a[OK]l[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]t[OK]o[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]:[OK] [OK]{[OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]N[OK]e[OK]w[OK] [OK]f[OK]i[OK]l[OK]e[OK] [OK]s[OK]i[OK]z[OK]e[OK]:[OK] [OK]{[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]-[OK] [OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]R[OK]e[OK]d[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]:[OK] [OK]{[OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK]_[OK]t[OK]o[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]/[OK] [OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]:[OK].[OK]1[OK]f[OK]}[OK]%[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]{[OK]'[OK]=[OK]'[OK]*[OK]7[OK]0[OK]}[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]d[OK]r[OK]y[OK]_[OK]r[OK]u[OK]n[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]D[OK]R[OK]Y[OK] [OK]R[OK]U[OK]N[OK] [OK]M[OK]O[OK]D[OK]E[OK] [OK]-[OK] [OK]N[OK]o[OK] [OK]c[OK]h[OK]a[OK]n[OK]g[OK]e[OK]s[OK] [OK]m[OK]a[OK]d[OK]e[OK] [OK]t[OK]o[OK] [OK]f[OK]i[OK]l[OK]e[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]T[OK]o[OK] [OK]a[OK]c[OK]t[OK]u[OK]a[OK]l[OK]l[OK]y[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK],[OK] [OK]r[OK]u[OK]n[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]-[OK]-[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK] [OK]f[OK]l[OK]a[OK]g[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]P[OK]e[OK]r[OK]f[OK]o[OK]r[OK]m[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK] [OK]([OK]f[OK]r[OK]o[OK]m[OK] [OK]b[OK]o[OK]t[OK]t[OK]o[OK]m[OK] [OK]t[OK]o[OK] [OK]t[OK]o[OK]p[OK] [OK]s[OK]o[OK] [OK]l[OK]i[OK]n[OK]e[OK] [OK]n[OK]u[OK]m[OK]b[OK]e[OK]r[OK]s[OK] [OK]s[OK]t[OK]a[OK]y[OK] [OK]v[OK]a[OK]l[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK] [OK]=[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]s[OK]t[OK]a[OK]r[OK]t[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]n[OK]d[OK] [OK]=[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]e[OK]n[OK]d[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK] [OK]=[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]o[OK]t[OK]e[OK] [OK]=[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]n[OK]o[OK]t[OK]e[OK]'[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]R[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]#[OK] [OK]R[OK]E[OK]M[OK]O[OK]V[OK]E[OK]D[OK]:[OK] [OK]{[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]}[OK]\[OK]n[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]#[OK] [OK]N[OK]o[OK]w[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]d[OK] [OK]b[OK]y[OK] [OK]b[OK]a[OK]c[OK]k[OK]e[OK]n[OK]d[OK]/[OK]a[OK]p[OK]p[OK]/[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]s[OK]/[OK]{[OK]r[OK]o[OK]u[OK]t[OK]e[OK]r[OK]}[OK]\[OK]n[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]f[OK]"[OK]#[OK] [OK]N[OK]o[OK]t[OK]e[OK]:[OK] [OK]{[OK]n[OK]o[OK]t[OK]e[OK]}[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]"[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]R[OK]e[OK]m[OK]o[OK]v[OK]e[OK] [OK]t[OK]h[OK]e[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]n[OK]d[OK] [OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK][[OK]s[OK]t[OK]a[OK]r[OK]t[OK]:[OK]e[OK]n[OK]d[OK]+[OK]1[OK]][OK] [OK]=[OK] [OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]‚[OK]ú[OK]ì[OK] [OK]R[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK]:[OK] [OK]{[OK]d[OK]e[OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK]i[OK]o[OK]n[OK]}[OK] [OK]([OK]{[OK]r[OK]e[OK]m[OK]o[OK]v[OK]a[OK]l[OK][[OK]'[OK]l[OK]i[OK]n[OK]e[OK]s[OK]'[OK]][OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]‚[OK]Ü[OK]í[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]c[OK]o[OK]m[OK]m[OK]e[OK]n[OK]t[OK]_[OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK] [OK]b[OK]a[OK]c[OK]k[OK] [OK]t[OK]o[OK] [OK]f[OK]i[OK]l[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]W[OK]r[OK]i[OK]t[OK]i[OK]n[OK]g[OK] [OK]c[OK]h[OK]a[OK]n[OK]g[OK]e[OK]s[OK] [OK]t[OK]o[OK] [OK]{[OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK]}[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK],[OK] [OK]'[OK]w[OK]'[OK],[OK] [OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK]=[OK]'[OK]u[OK]t[OK]f[OK]-[OK]8[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK].[OK]w[OK]r[OK]i[OK]t[OK]e[OK]l[OK]i[OK]n[OK]e[OK]s[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]=[OK] [OK]l[OK]e[OK]n[OK]([OK]l[OK]i[OK]n[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]c[OK]t[OK]u[OK]a[OK]l[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK] [OK]=[OK] [OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]-[OK] [OK]f[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]{[OK]'[OK]=[OK]'[OK]*[OK]7[OK]0[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]‚[OK]ú[OK]ì[OK] [OK]S[OK]U[OK]C[OK]C[OK]E[OK]S[OK]S[OK]![OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]O[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]:[OK] [OK]{[OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]F[OK]i[OK]n[OK]a[OK]l[OK]:[OK] [OK]{[OK]f[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]R[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK]:[OK] [OK]{[OK]a[OK]c[OK]t[OK]u[OK]a[OK]l[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK]}[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK] [OK]([OK]{[OK]a[OK]c[OK]t[OK]u[OK]a[OK]l[OK]_[OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK] [OK]/[OK] [OK]o[OK]r[OK]i[OK]g[OK]i[OK]n[OK]a[OK]l[OK]_[OK]l[OK]i[OK]n[OK]e[OK]_[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]:[OK].[OK]1[OK]f[OK]}[OK]%[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]{[OK]'[OK]=[OK]'[OK]*[OK]7[OK]0[OK]}[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK][OK]
[OK][OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]"[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]"[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]y[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK] [OK]=[OK] [OK]P[OK]a[OK]t[OK]h[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK].[OK]p[OK]a[OK]r[OK]e[OK]n[OK]t[OK] [OK]/[OK] [OK]"[OK]b[OK]a[OK]c[OK]k[OK]e[OK]n[OK]d[OK]"[OK] [OK]/[OK] [OK]"[OK]a[OK]p[OK]p[OK]"[OK] [OK]/[OK] [OK]"[OK]m[OK]a[OK]i[OK]n[OK].[OK]p[OK]y[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK].[OK]e[OK]x[OK]i[OK]s[OK]t[OK]s[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]E[OK]R[OK]R[OK]O[OK]R[OK]:[OK] [OK]C[OK]o[OK]u[OK]l[OK]d[OK] [OK]n[OK]o[OK]t[OK] [OK]f[OK]i[OK]n[OK]d[OK] [OK]{[OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]y[OK]s[OK].[OK]e[OK]x[OK]i[OK]t[OK]([OK]1[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]f[OK]o[OK]r[OK] [OK]-[OK]-[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK] [OK]f[OK]l[OK]a[OK]g[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK] [OK]=[OK] [OK]"[OK]-[OK]-[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]"[OK] [OK]i[OK]n[OK] [OK]s[OK]y[OK]s[OK].[OK]a[OK]r[OK]g[OK]v[OK] [OK]o[OK]r[OK] [OK]"[OK]-[OK]e[OK]"[OK] [OK]i[OK]n[OK] [OK]s[OK]y[OK]s[OK].[OK]a[OK]r[OK]g[OK]v[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]7[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]D[OK]R[OK]Y[OK] [OK]R[OK]U[OK]N[OK] [OK]M[OK]O[OK]D[OK]E[OK] [OK]-[OK] [OK]P[OK]r[OK]e[OK]v[OK]i[OK]e[OK]w[OK] [OK]o[OK]n[OK]l[OK]y[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]7[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]_[OK]d[OK]u[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]e[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]([OK]m[OK]a[OK]i[OK]n[OK]_[OK]p[OK]y[OK]_[OK]p[OK]a[OK]t[OK]h[OK],[OK] [OK]d[OK]r[OK]y[OK]_[OK]r[OK]u[OK]n[OK]=[OK]n[OK]o[OK]t[OK] [OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]n[OK]o[OK]t[OK] [OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]T[OK]o[OK] [OK]a[OK]p[OK]p[OK]l[OK]y[OK] [OK]t[OK]h[OK]e[OK]s[OK]e[OK] [OK]c[OK]h[OK]a[OK]n[OK]g[OK]e[OK]s[OK],[OK] [OK]r[OK]u[OK]n[OK]:[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]p[OK]y[OK]t[OK]h[OK]o[OK]n[OK] [OK]{[OK]P[OK]a[OK]t[OK]h[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK].[OK]n[OK]a[OK]m[OK]e[OK]}[OK] [OK]-[OK]-[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]"[OK])[OK][OK]
[OK]
