"""Add baseline and organization pattern tables

Revision ID: 04131ed40cc0
Revises: 20251213_remove_legacy
Create Date: 2025-12-14 05:30:40.897142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04131ed40cc0'
down_revision = '20251213_remove_legacy'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_scan_id'), 'baselines', ['scan_id'], unique=False)
    op.create_table('organization_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('pattern_variants', sa.JSON(), nullable=False),
    sa.Column('pattern_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('last_seen_scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_patterns_canonical_name'), 'organization_patterns', ['canonical_name'], unique=True)
    op.drop_index(op.f('ix_company_domain'), table_name='company')
    op.create_index(op.f('ix_company_company_domain'), 'company', ['company_domain'], unique=False)
    op.drop_index(op.f('idx_weight_audit_changed_at'), table_name='confidence_weight_audit')
    op.drop_index(op.f('idx_weight_audit_org'), table_name='confidence_weight_audit')
    op.drop_index(op.f('idx_confidence_weights_org'), table_name='confidence_weights')
    op.drop_column('confidence_weights', 'id_format_weight')
    op.alter_column('control', 'financial_assertions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_control_confidence'), table_name='control')
    op.drop_index(op.f('idx_control_merged_to'), table_name='control')
    op.drop_index(op.f('idx_control_pdf_snippet'), table_name='control', postgresql_using='gin')
    op.drop_index(op.f('idx_control_scan_id'), table_name='control')
    op.drop_index(op.f('idx_control_scan_merged'), table_name='control')
    op.drop_column('control', 'control_tsc_mappings_backup')
    op.drop_column('control', 'pdf_snippet')
    op.drop_column('control', 'control_coso_mappings_backup')
    op.drop_index(op.f('idx_pattern_org'), table_name='control_pattern')
    op.drop_index(op.f('idx_control_review_org'), table_name='control_review')
    op.drop_index(op.f('idx_control_review_scan'), table_name='control_review')
    op.drop_index(op.f('idx_control_review_status'), table_name='control_review')
    op.drop_index(op.f('idx_cuec_pdf_snippet'), table_name='cuec', postgresql_using='gin')
    op.drop_index(op.f('idx_cuec_scan_id'), table_name='cuec')
    op.drop_column('cuec', 'cuec_coso_mappings_backup')
    op.drop_column('cuec', 'pdf_snippet')
    op.drop_column('cuec', 'cuec_tsc_mappings_backup')
    op.drop_index(op.f('ix_report_type_detections_created_at'), table_name='report_type_detections')
    op.alter_column('scan', 'is_sox_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_scan_report_type'), table_name='scan')
    op.drop_index(op.f('idx_scan_sections'), table_name='scan', postgresql_using='gin')
    op.drop_column('scan', 'sections')
    op.drop_column('scan', 'control_id_pattern_analysis')
    op.drop_index(op.f('idx_suborg_scan_id'), table_name='subservice_org')
    op.drop_index(op.f('idx_subservice_org_pdf_snippet'), table_name='subservice_org', postgresql_using='gin')
    op.drop_column('subservice_org', 'pdf_snippet')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subservice_org', sa.Column('pdf_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_subservice_org_pdf_snippet'), 'subservice_org', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(pdf_snippet, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_suborg_scan_id'), 'subservice_org', ['scan_id'], unique=False)
    op.add_column('scan', sa.Column('control_id_pattern_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_scan_sections'), 'scan', ['sections'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scan_report_type'), 'scan', ['report_type'], unique=False)
    op.alter_column('scan', 'is_sox_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_report_type_detections_created_at'), 'report_type_detections', ['created_at'], unique=False)
    op.add_column('cuec', sa.Column('cuec_tsc_mappings_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('cuec', sa.Column('pdf_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cuec', sa.Column('cuec_coso_mappings_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_cuec_scan_id'), 'cuec', ['scan_id'], unique=False)
    op.create_index(op.f('idx_cuec_pdf_snippet'), 'cuec', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(pdf_snippet, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_control_review_status'), 'control_review', ['review_status'], unique=False)
    op.create_index(op.f('idx_control_review_scan'), 'control_review', ['scan_id', 'review_status'], unique=False)
    op.create_index(op.f('idx_control_review_org'), 'control_review', ['organization'], unique=False)
    op.create_index(op.f('idx_pattern_org'), 'control_pattern', ['organization', 'pattern'], unique=False)
    op.add_column('control', sa.Column('control_coso_mappings_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('control', sa.Column('pdf_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('control', sa.Column('control_tsc_mappings_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_control_scan_merged'), 'control', ['scan_id', 'merged_to_control_id'], unique=False)
    op.create_index(op.f('idx_control_scan_id'), 'control', ['scan_id'], unique=False)
    op.create_index(op.f('idx_control_pdf_snippet'), 'control', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(pdf_snippet, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_control_merged_to'), 'control', ['merged_to_control_id'], unique=False)
    op.create_index(op.f('idx_control_confidence'), 'control', ['control_confidence'], unique=False)
    op.alter_column('control', 'financial_assertions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('confidence_weights', sa.Column('id_format_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.1'::double precision"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_confidence_weights_org'), 'confidence_weights', ['organization'], unique=True)
    op.create_index(op.f('idx_weight_audit_org'), 'confidence_weight_audit', ['organization'], unique=False)
    op.create_index(op.f('idx_weight_audit_changed_at'), 'confidence_weight_audit', ['changed_at'], unique=False)
    op.drop_index(op.f('ix_company_company_domain'), table_name='company')
    op.create_index(op.f('ix_company_domain'), 'company', ['company_domain'], unique=False)
    op.drop_index(op.f('ix_organization_patterns_canonical_name'), table_name='organization_patterns')
    op.drop_table('organization_patterns')
    op.drop_index(op.f('ix_baselines_scan_id'), table_name='baselines')
    op.drop_table('baselines')
    # ### end Alembic commands ###

