"""init schema

Revision ID: 449ae1762a28
Revises: 
Create Date: 2025-08-11 22:34:43.995897

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '449ae1762a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_company', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.String(length=128), nullable=True),
    sa.Column('control_desc', sa.Text(), nullable=True),
    sa.Column('control_test', sa.Text(), nullable=True),
    sa.Column('control_test_results', sa.Text(), nullable=True),
    sa.Column('control_page_ref', sa.Integer(), nullable=True),
    sa.Column('control_line_ref', sa.Integer(), nullable=True),
    sa.Column('control_seq', sa.Integer(), nullable=True),
    sa.Column('control_tsc_id', sa.String(length=128), nullable=True),
    sa.Column('control_coso_id', sa.String(length=128), nullable=True),
    sa.Column('control_tsc_similarity', sa.Float(), nullable=True),
    sa.Column('control_coso_similarity', sa.Float(), nullable=True),
    sa.Column('control_tsc_confidence_pct', sa.Integer(), nullable=True),
    sa.Column('control_coso_confidence_pct', sa.Integer(), nullable=True),
    sa.Column('control_closest_framework', sa.String(length=128), nullable=True),
    sa.Column('control_tsc_section', sa.String(length=128), nullable=True),
    sa.Column('control_coso_section', sa.String(length=128), nullable=True),
    sa.Column('control_soc_domain', sa.String(length=128), nullable=True),
    sa.Column('control_status', sa.String(length=64), nullable=True),
    sa.Column('merged_to_control_id', sa.String(length=128), nullable=True),
    sa.Column('control_gpt_opinion', sa.Text(), nullable=True),
    sa.Column('control_gpt_reasoning', sa.Text(), nullable=True),
    sa.Column('control_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_calc', sa.Text(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuec',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuec_seq', sa.Integer(), nullable=True),
    sa.Column('cuec_tsc_id', sa.String(length=128), nullable=True),
    sa.Column('cuec_description', sa.Text(), nullable=True),
    sa.Column('cuec_line_ref', sa.Integer(), nullable=True),
    sa.Column('cuec_confidence', sa.Float(), nullable=True),
    sa.Column('cuec_gpt_opinion', sa.String(length=32), nullable=True),
    sa.Column('cuec_distance_from_cuec_keywords', sa.Integer(), nullable=True),
    sa.Column('cuec_gpt_reasoning', sa.Text(), nullable=True),
    sa.Column('cuec_framework_alignment', sa.String(length=128), nullable=True),
    sa.Column('cuec_framework_alignment_id', sa.String(length=128), nullable=True),
    sa.Column('cuec_justification', sa.Text(), nullable=True),
    sa.Column('cuec_coso_id', sa.String(length=128), nullable=True),
    sa.Column('cuec_tsc_similarity', sa.Float(), nullable=True),
    sa.Column('cuec_coso_similarity', sa.Float(), nullable=True),
    sa.Column('cuec_tsc_confidence_pct', sa.Integer(), nullable=True),
    sa.Column('cuec_coso_confidence_pct', sa.Integer(), nullable=True),
    sa.Column('cuec_closest_framework', sa.String(length=128), nullable=True),
    sa.Column('cuec_confidence_justification', sa.Text(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('control_strength', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('coverage_start', sa.DateTime(), nullable=True),
    sa.Column('coverage_end', sa.DateTime(), nullable=True),
    sa.Column('pdf_file', sa.LargeBinary(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=256), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('gpt_cost', sa.Float(), nullable=True),
    sa.Column('gpt_model', sa.String(length=128), nullable=True),
    sa.Column('estimated_time_seconds', sa.Float(), nullable=True),
    sa.Column('auditor', sa.Text(), nullable=True),
    sa.Column('gpt_usage_details', sa.JSON(), nullable=True),
    sa.Column('executive_summary', sa.JSON(), nullable=True),
    sa.Column('executive_summary_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subservice_org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('third_party_description', sa.Text(), nullable=True),
    sa.Column('third_party_page_ref', sa.Text(), nullable=True),
    sa.Column('third_party_confidence', sa.Float(), nullable=True),
    sa.Column('distance_from_so_keywords', sa.Float(), nullable=True),
    sa.Column('likely_so', sa.String(length=64), nullable=True),
    sa.Column('common_so', sa.String(length=64), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('confidence_justification', sa.Text(), nullable=True),
    sa.Column('third_party_controls', sa.JSON(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subservice_org')
    op.drop_table('settings')
    op.drop_table('scan')
    op.drop_table('product')
    op.drop_table('cuec')
    op.drop_table('control')
    op.drop_table('company')
    # ### end Alembic commands ###

