"""add deviation fields to control

Revision ID: 6f860bd14eac
Revises: 449ae1762a28
Create Date: 2025-08-13 21:56:19.916287

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6f860bd14eac'
down_revision = '449ae1762a28'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

