"""drop unique constraint on control scan_id control_id

Revision ID: 760221175d38
Revises: ceefce4245b1
Create Date: 2026-02-19 10:38:17.966699

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '760221175d38'
down_revision = 'ceefce4245b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

