"""add objective confidence_metadata field for audit trail

Revision ID: 7db38ce025c3
Revises: 20260203_add_mapping_justification
Create Date: 2026-02-14 23:02:10.790420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7db38ce025c3'
down_revision = '20260203_add_mapping_justification'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_config_extractor_name'), table_name='model_config')
    op.drop_table('model_config')
    op.drop_constraint(op.f('fk_baselines_user'), 'baselines', type_='foreignkey')
    op.drop_column('baselines', 'user_id')
    op.drop_index(op.f('idx_company_scan_confidence'), table_name='company')
    op.drop_constraint(op.f('fk_confidence_weight_audit_user'), 'confidence_weight_audit', type_='foreignkey')
    op.drop_column('confidence_weight_audit', 'changed_by_user_id_new')
    op.alter_column('control', 'primary_criterion_id_normalized',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Normalized criterion ID for consistent display/sorting',
               existing_nullable=True)
    op.alter_column('control', 'primary_criterion_id_original',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Original criterion ID format from report for accurate searching',
               existing_nullable=True)
    op.add_column('control_objectives', sa.Column('confidence_metadata', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('fk_control_review_user'), 'control_review', type_='foreignkey')
    op.alter_column('cuec', 'primary_criterion_id_normalized',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Normalized criterion ID for consistent display/sorting',
               existing_nullable=True)
    op.alter_column('cuec', 'primary_criterion_id_original',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Original criterion ID format from report for accurate searching',
               existing_nullable=True)
    op.create_foreign_key(None, 'cuec', 'users', ['updated_by_user_id'], ['id'])
    op.drop_column('cuec_objective_mappings', 'mapping_justification')
    op.drop_column('cuec_objective_mappings', 'objective_gpt_confidence_boost')
    op.drop_constraint(op.f('fk_pattern_review_rejected_by'), 'pattern_review_queue', type_='foreignkey')
    op.drop_constraint(op.f('fk_pattern_review_approved_by'), 'pattern_review_queue', type_='foreignkey')
    op.drop_column('pattern_review_queue', 'approved_by_user_id')
    op.drop_column('pattern_review_queue', 'rejected_by_user_id')
    op.alter_column('scan', 'pattern_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_scan_date_desc'), table_name='scan')
    op.drop_index(op.f('ix_scan_user_id'), table_name='scan')
    op.drop_constraint(op.f('fk_scan_user'), 'scan', type_='foreignkey')
    op.drop_column('scan', 'user_id')
    op.create_foreign_key(None, 'subservice_org', 'users', ['updated_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subservice_org', type_='foreignkey')
    op.add_column('scan', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_scan_user'), 'scan', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_scan_user_id'), 'scan', ['user_id'], unique=False)
    op.create_index(op.f('idx_scan_date_desc'), 'scan', [sa.literal_column('scan_date DESC')], unique=False)
    op.alter_column('scan', 'pattern_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('pattern_review_queue', sa.Column('rejected_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pattern_review_queue', sa.Column('approved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_pattern_review_approved_by'), 'pattern_review_queue', 'users', ['approved_by_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_pattern_review_rejected_by'), 'pattern_review_queue', 'users', ['rejected_by_user_id'], ['id'])
    op.add_column('cuec_objective_mappings', sa.Column('objective_gpt_confidence_boost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cuec_objective_mappings', sa.Column('mapping_justification', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cuec', type_='foreignkey')
    op.alter_column('cuec', 'primary_criterion_id_original',
               existing_type=sa.VARCHAR(length=128),
               comment='Original criterion ID format from report for accurate searching',
               existing_nullable=True)
    op.alter_column('cuec', 'primary_criterion_id_normalized',
               existing_type=sa.VARCHAR(length=128),
               comment='Normalized criterion ID for consistent display/sorting',
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_control_review_user'), 'control_review', 'users', ['reviewed_by_user_id'], ['id'])
    op.drop_column('control_objectives', 'confidence_metadata')
    op.alter_column('control', 'primary_criterion_id_original',
               existing_type=sa.VARCHAR(length=128),
               comment='Original criterion ID format from report for accurate searching',
               existing_nullable=True)
    op.alter_column('control', 'primary_criterion_id_normalized',
               existing_type=sa.VARCHAR(length=128),
               comment='Normalized criterion ID for consistent display/sorting',
               existing_nullable=True)
    op.add_column('confidence_weight_audit', sa.Column('changed_by_user_id_new', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_confidence_weight_audit_user'), 'confidence_weight_audit', 'users', ['changed_by_user_id_new'], ['id'])
    op.create_index(op.f('idx_company_scan_confidence'), 'company', ['scan_id', 'confidence', 'id'], unique=False)
    op.add_column('baselines', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_baselines_user'), 'baselines', 'users', ['user_id'], ['id'])
    op.create_table('model_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extractor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('model_config_pkey')),
    sa.UniqueConstraint('extractor_name', name=op.f('uq_model_config_extractor_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_model_config_extractor_name'), 'model_config', ['extractor_name'], unique=False)
    # ### end Alembic commands ###

