"""add unique constraint on control_objective_mappings

Revision ID: 9a37bd62db73
Revises: 723d5fe653f5
Create Date: 2026-02-17 10:05:28.318846

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9a37bd62db73'
down_revision = '723d5fe653f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

