"""add all_line_refs mapping_feedback

Revision ID: bab72709240c
Revises: e7f5db2f2139
Create Date: 2026-02-18 18:02:07.232847

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bab72709240c'
down_revision = 'e7f5db2f2139'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('original_method', sa.String(length=32), nullable=True),
    sa.Column('control_id_text', sa.String(length=128), nullable=True),
    sa.Column('control_desc_snippet', sa.Text(), nullable=True),
    sa.Column('objective_id_text', sa.String(length=128), nullable=True),
    sa.Column('objective_text_snippet', sa.Text(), nullable=True),
    sa.Column('redirected_to_objective_id', sa.Integer(), nullable=True),
    sa.Column('redirected_to_objective_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['control_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['redirected_to_objective_id'], ['control_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_feedback_scan_id'), 'mapping_feedback', ['scan_id'], unique=False)
    op.add_column('control', sa.Column('all_line_refs', sa.JSON(), nullable=True))
    op.add_column('control_objectives', sa.Column('all_line_refs', sa.JSON(), nullable=True))
    op.add_column('control_objectives', sa.Column('all_page_refs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_objectives', 'all_page_refs')
    op.drop_column('control_objectives', 'all_line_refs')
    op.drop_column('control', 'all_line_refs')
    op.drop_index(op.f('ix_mapping_feedback_scan_id'), table_name='mapping_feedback')
    op.drop_table('mapping_feedback')
    # ### end Alembic commands ###

