"""add control_feedback table

Revision ID: ceefce4245b1
Revises: bab72709240c
Create Date: 2026-02-18 18:10:17.000520

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ceefce4245b1'
down_revision = 'bab72709240c'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('control_db_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('control_id_text', sa.String(length=128), nullable=True),
    sa.Column('control_desc_snippet', sa.Text(), nullable=True),
    sa.Column('corrected_control_id', sa.String(length=128), nullable=True),
    sa.Column('rejection_reason', sa.String(length=64), nullable=True),
    sa.Column('rejection_notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_db_id'], ['control.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_feedback_scan_id'), 'control_feedback', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_feedback_scan_id'), table_name='control_feedback')
    op.drop_table('control_feedback')
    # ### end Alembic commands ###

