"""add confirmed fields to control_objective_mappings

Revision ID: e7f5db2f2139
Revises: 3df81a8eedf6
Create Date: 2026-02-18 00:36:09.045591

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e7f5db2f2139'
down_revision = '3df81a8eedf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_objective_mappings', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('control_objective_mappings', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('control_objective_mappings', sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'control_objective_mappings', 'users', ['confirmed_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_objective_mappings', type_='foreignkey')
    op.drop_column('control_objective_mappings', 'confirmed_by_user_id')
    op.drop_column('control_objective_mappings', 'confirmed_at')
    op.drop_column('control_objective_mappings', 'confirmed')
    # ### end Alembic commands ###

